name: deploy to azure
on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: Assign1 
      uses: actions/checkout@master

    - name: Setup Node 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: 'npm install, build, and test'
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: new-1
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}